kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-k8s-server-config-dev
data:
  application.yml: |-
    greeting:
      message: Say Hello to the Developers
    farewell:
      message: Say Goodbye to the Developers