spring:
  application:
    name: spring-k8s-server
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        include-not-ready-addresses: true
        primary-port-name: http
      config:
        sources:
          - name: spring-k8s-server-config
server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"