apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: spring-cloud-account
  labels:
    k8s-app: spring-cloud
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: spring-cloud-cr
  labels:
    k8s-app: spring-cloud
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "endpoints"
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud-crb
  labels:
    k8s-app: spring-cloud
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: spring-cloud-account
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: endpoints-reader
  apiGroup: ""