kind: Service
apiVersion: v1
metadata:
  labels:
    app: spring-k8s-server-app
  name: spring-k8s-server-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 38080
  selector:
    app: spring-k8s-server-app
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: spring-k8s-server-app
  name: spring-k8s-server-app
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 15
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spring-k8s-server-app
  template:
    metadata:
      labels:
        app: spring-k8s-server-app
    spec:
      #hostNetwork: true
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      serviceAccountName: spring-cloud-account
      containers:
        - name: spring-k8s-server
          image: image:v
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"