kind: Service
apiVersion: v1
metadata:
  labels:
    app: {artifactId}-app
  name: {artifactId}-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: app
      port: 8080
      targetPort: 8080
      nodePort: 38080
    - name: manage
      port: 8081
      targetPort: 8081
      nodePort: 38081
  selector:
    app: {artifactId}-app
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {artifactId}-app
  name: {artifactId}-app
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 15
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {artifactId}-app
  template:
    metadata:
      labels:
        app: {artifactId}-app
    spec:
      #hostNetwork: true
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      serviceAccountName: spring-cloud-account
      containers:
        - name: {artifactId}
          image: {image:v}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {profile}